#include <stdio.h>

#include "test.h"
#include "matrix.h"
#include "strassen.h"

int main(int argc, char *argv[]) {
  size_t n = 1 << 12;

  // Uncomment this for loop if you want to see the results of more than one execution of the multiplication.
  // Remember to close the for loop after the deallocation of the matrices, in the end.
  // The alternative is to put a higher value for rep in test.c.
  //for(int i = 0; i < 5; i ++){

    float **A = allocate_random_matrix(n, n);
    float **B = allocate_random_matrix(n, n);
    float **C0 = allocate_matrix(n, n);
    float **C1 = allocate_matrix(n, n);
    float **C2 = allocate_matrix(n, n);


    printf("n\tStrassen's Alg.\tImproved Alg.\tNaive Alg.\tSame result\n");

    for (size_t j = 1; j <= n; j *= 2) {

      printf("%ld\t", j);
      fflush(stdout);
      
      // classic Strassen's algorithm 
      printf("%lf\t", test(strassen_matrix_multiplication, C1, A, B, j));
      fflush(stdout);
      
      // improved Strassen's algorithm
      printf("%lf\t", test(strassen_matrix_multiplication_improved, C2, A, B, j));
      fflush(stdout);
      
      // naive matrix multiplication
      printf("%lf\t", test(naive_matrix_multiplication, C0, A, B, j));
      fflush(stdout);

      // check if the two matrices, generated by the Strassen's algorithm and the naive one, are the same
      printf("%d\n", same_matrix((float const *const *const)C0, (float const *const *const)C1, j, j));
    }
  
  

  deallocate_matrix(A, n);
  deallocate_matrix(B, n);
  deallocate_matrix(C0, n);
  deallocate_matrix(C1, n);
  deallocate_matrix(C2, n);
  
  

  return 0;
}
